<?xml version="1.0"?>
<package format="3">
  <name>nav2_rl_project</name>
  <version>1.0.0</version>
  <description>
    Reinforcement-learning local navigation for TurtleBot3 using Nav2 global paths in Gazebo simulation and on real hardware.
  </description>

  <maintainer email="vasanmathi1999@gmail.com">Mathiyalagan Vasantharaj</maintainer>
<author>Mathiyalagan Vasantharaj</author>
<author>Isaac Vivin Moses</author>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>gazebo_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
